### PR TITLE
Array and Vector support

### PR DESCRIPTION
**Pull request by filmackay**
Add LLVM Array and Vector support.

### CODE REVIEW

**Comment by markflorisson** [comment]
Cool. I rebased on the 'builder' branch and added some fixes in the 'vectors' branch:

```
https://github.com/pykit/pykit/tree/vectors
```

test_vectors doesn't parse for me for some reason though. I didn't see a test for arrays. If you want you can fork these changes and add a test and run it with 'python runtests.py'. (Don't try pulling these changes into your branch, since I the branch)

**Comment by filmackay** [comment]
OK, so I should delete my fork and re-fork from vector branch? Should I then do a PR to get my changes back in, or permission you on my fork?

**Comment by markflorisson** [comment]
Yeah you can leave it or delete it, and just fork it and do a new PR with your changes.

**Comment by markflorisson** [comment]
Regarding the gep instruction, can we do with just getelement, getfield and the likes?

**Comment by markflorisson** [comment]
I'd really like to keep the number of opcodes down, which can simplify a whole bunch of passes and the IR interpreter. What do you think of just keeping getfield/setfield and getindex/setindex, and removing {insert,extract}{value,element} and gep?

**Comment by filmackay** [comment]
The main reason I want gep is to be able to efficient cast between vector and an int / array of ints. I could probably achieve that with a cast/convert like operation instead, which would generate a gep only at LLVM IR?

I'll make these changes in my fork and you can check it out and see what you think..

What is the purpose of getfield/setfield - never quite understood that one. It seems to be named members on an object, as opposed to indexed.. what kind of "objects" does this apply to though?

**Comment by markflorisson** [comment]
Cool :) I don't think you can/should gep a vector, but it should be possible to store one. Just cast the array to a pointer of a vector, and store the vector in there.

getfield/setfield are for structs to preserve names, but also for object attribute access.

**Comment by filmackay** [comment]
Yes, don't gep the vector - but you need gep to get the address of the array, no? Then cast to a vector pointer, and get/store from there. Bitcast would be necessary too to do a direct int --> vector conversion without going via a pointer I guess too. I suppose this is where the power of pykit comes in - one logical operation (cast/convert) can morph into a number of different strategies at LLVM level..

**Comment by markflorisson** [comment]
Yeah exactly, it doesn't really matter how the code generator implements it except for performance, but we can keep our IR clean and easy to use :)

**Comment by filmackay** [comment]
Can I suggest this - unify get/set method that operates on all object/struct/array to simplify the IR even further:
- array/struct: map to LLVM insertvalue/extractvalue
- vector: map to LLVM insertelement/extractelement
- objects: get/set attributes

It would support both integer and string indices, meaning you could:

builder.get(s, ["agg", 3]) # struct contains a field "agg" which is an array, get the item #3 of array
builder.get(v, 0) # get first element in vector

If you think the multi-level capability is useless in pykit, we could still make it universal but just accept one level. Presumably you'd cascade them to get multi-level then - as long as it optimises down nicely..

Incidentally, ops getfield and extractfield seem redundant (one uses gep-store, the other extractvalue). Both can be replaced with get() above?

**Comment by filmackay** [comment]
If I wanted to have a "vector to int" operation, that took a vector and turned it into a single integer (eg. Vector(Int32, 4) ==> UInt32(128)): where would this belong? Does it make no sense to put in pykit (leave as a bitcast op), but implement in numba2?

Similarly I want a "vector to array" (and visa versa). The advantage of doing it as a pykit op is that it becomes type-safe, as opposed to doing it manually via ptrcast()?

**Comment by filmackay** [comment]
test_vectors was from generations ago, not relevant any more. where should I put the vector/array tests - and what sorts of things should I test? the IR generated, or the actual operation correctness - should I put them in test_ops?

**Comment by markflorisson** [comment]
I'd like to distinguish between indexing and attribute access, which needs to be handled differently in a variety of places in numba. But pykit can follow its own rules of course, so it's not a requirement by any means. My course of action so far has been to make things polymorphic at the type level, but distinguish at the syntax level:

```
 a + b -> add(a, b)  for int, float
 obj.a -> getfield     for records/objects
 obj[a] -> getindex  for indexables
```

But yeah, extractfield is redundant. It was introduced at some point to deal with struct.attr vs struct_p->attr, but I don't think it's needed any longer. You can probably remove it, but do check if it doesn't totally break numba :).

Regarding the vector casting, it's up to you. If you think a vector cast is really needed, go for it. But keep in mind that adding ops generally adds greater complexity, and you may need a compiler pass that does the type check. I think it might be easier to just do that check in the implementation of the opaque function in numba.

I would put any operations that use arithmetic/math in test_ops, but array and vector specific stuff such as indexing in its own file, probably in a code generator test package somewhere. But whatever seems logical to you should be fine :)

**Comment by filmackay** [comment]
To follow up, I've ended up unifying into single "get" and "set" operations that work for struct, array and vector. Looks nice and clean.

Numba2's Vector has to_array/from_array that store/load's the Vector value from a pointer to an array of the same size as the vector.

**Pull request closed without merging**
